### ISSUE TITLE
Add login limit to account

### ISSUE THREAD

**Issue by Chiiruno** [Chiiruno/meguca#45]
https://github.com/bakape/meguca/issues/747

**Comment by rsdr** [comment]
You could log these login attempts via a table as suggested in the previous repository, specifically noting the username used in the attempt. Probably include time, username entered and success check. Ignoring successful attempts isn't in the issue, since (from what I've read from the previous repository) this is just to prevent too many sessions. 

Please ignore this if it is of no help. I'm not experienced when it comes to Github.
